### PR TITLE
Improve name positioning and update example/Readme

### PR DESCRIPTION
**Pull request by Silmathoron**
This PR improves name positioning and rotation.
It also updates Readme docstring and contributors as well as the example to show all possibilities.

@gph82 could you review this PR to check that it fixes your previous issues with name positioning?

### CODE REVIEW

**Comment by Silmathoron** [comment]
@gph82 sorry to up this but I just wanted to know whether you would have time to look at it at some point or if I should just merge this directly ;)

**Review by gph82 — APPROVED** [review]
LGTM

**Comment by gph82** [comment]
Just approved, sorry, was away on my own projects this week, thanks for reminding :)

**Comment by Silmathoron** [comment]
No worries, thanks a lot for checking, did it solve the issues you mentioned before then?

**Comment by gph82** [comment]
Good call, i had forgotten about them. I just pulled this branch, I will re-run the notebooks and let you know

**Comment by gph82** [comment]
I guess you mean my comment here https://github.com/Silmathoron/mpl_chord_diagram/pull/18#issue-528618860
"Next up: text label placing (probably an va="middle" has to be set somewhere", right? 
I cannot run the exact same notebook but I've checked with a couple of options and I do not encounter this. Textlabels are nicely "padded" away from the arcs. It's good we double checked.

**Pull request merged**
